config/routes.rb
Rails.application.routes.draw do
  resources :repairs
  resources :provas
  resources :assistances
  get 'home/index'

  root to: "home#index"
  resources :estimates
  resources :devices
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estimate.rb
class Estimate < ApplicationRecord
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]
  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
  end

  # GET /estimates/new
  def new
    @estimate = Estimate.new
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)
    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: 'Estimate was successfully created.' }
        format.json { render :show, status: :created, location: @estimate }
      else
        format.html { render :new }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to @estimate, notice: 'Estimate was successfully updated.' }
        format.json { render :show, status: :ok, location: @estimate }
      else
        format.html { render :edit }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate.destroy
    respond_to do |format|
      format.html { redirect_to estimates_url, notice: 'Estimate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
        params.require(:estimate).permit(:username, :tipo, :issue, :other, :description, :pdf)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= form_with(model: estimate, local: true) do |form| %>
  <% if estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
      <% estimate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :estimate_username %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :estimate_tipo %>
  </div>

  <div class="field">
    <%= form.label :issue %>
    <%= form.text_field :issue, id: :estimate_issue %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.text_field :other, id: :estimate_other %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :estimate_description %>
  </div>

<!--
  <div class="field">
    <%= form.label :pdf %>
    <%= form.file_field :pdf, id: :estimate_pdf %>
  </div>
-->

    <style>
        .NoneVis {
            visibility: hidden
        }
    </style>
    <div>
        <label for="filePicker">Load Estimate:</label><br>
        <input type="file" id="filePicker">
    </div>
    <div class="NoneVis">
        <%= form.label :pdf %>
        <%= form.text_field :pdf, id: :estimate_pdf %>
    </div>
    <div class="actions">
        <%= form.submit %>
    </div>

    <script>
        var handleFileSelect = function(evt) {
        var files = evt.target.files;
        var file = files[0];
        
        if (files && file) {
            var reader = new FileReader();
            reader.onload = function(readerEvt) {
                var binaryString = readerEvt.target.result;
                document.getElementById("estimate_pdf").value = btoa(binaryString);
            };
        reader.readAsBinaryString(file);
        }
        };
        if (window.File && window.FileReader && window.FileList && window.Blob) {
            document.getElementById('filePicker').addEventListener('change', handleFileSelect, false);
        } else {
            alert('The File APIs are not fully supported in this browser.');
        }
    </script>

<% end %>

app/views/estimates/edit.html.erb
<h1>Editing Estimate</h1>

<%= render 'form', estimate: @estimate %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/index.html.erb
<style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }
        .topnav {
            overflow: hidden;
            background-color: #333;
        }
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        } 

        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }
</style>
<div class="topnav">
        <a href="./">Home</a>
        <a href="users">Users</a>
        <a class="active" href="estimates">Estimates</a>
        <a href="devices">Devices</a>
        <a href="assistances">Assistances</a>
        <a href="repairs">Repairs</a>
</div>

<p id="notice"><%= notice %></p>
<div style="padding-left:16px">

<table border="1">
  <thead>
    <tr>
      <th>Username</th>
      <th>Tipo</th>
      <th>Issue</th>
      <th>Other</th>
      <th>Description</th>
      <th>Pdf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= estimate.username %></td>
        <td><%= estimate.tipo %></td>
        <td><%= estimate.issue %></td>
        <td><%= estimate.other %></td>
        <td><%= estimate.description %></td>
        <td><%= estimate.pdf %></td>
        <td><%= link_to 'Show', estimate %></td>
        <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
        <td><%= link_to 'Destroy', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estimate', new_estimate_path %>
</div>

app/views/estimates/new.html.erb
<h1>New Estimate</h1>

<%= render 'form', estimate: @estimate %>

<%= link_to 'Back', estimates_path %>

app/views/estimates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @estimate.username %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @estimate.tipo %>
</p>

<p>
  <strong>Issue:</strong>
  <%= @estimate.issue %>
</p>

<p>
  <strong>Other:</strong>
  <%= @estimate.other %>
</p>

<p>
  <strong>Description:</strong>
  <%= @estimate.description %>
</p>

<p>
  <strong>Pdf:</strong>
  <%= @estimate.pdf %>
</p>

<%= link_to 'Edit', edit_estimate_path(@estimate) %> |
<%= link_to 'Back', estimates_path %>