config/routes.rb
Rails.application.routes.draw do
  resources :repairs
  resources :provas
  resources :assistances
  get 'home/index'

  root to: "home#index"
  resources :estimates
  resources :devices
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assistance.rb
class Assistance < ApplicationRecord
end

app/controllers/assistances_controller.rb
class AssistancesController < ApplicationController
  before_action :set_assistance, only: [:show, :edit, :update, :destroy]

  # GET /assistances
  # GET /assistances.json
  def index
    @assistances = Assistance.all
  end

  # GET /assistances/1
  # GET /assistances/1.json
  def show
  end

  # GET /assistances/new
  def new
    @assistance = Assistance.new
  end

  # GET /assistances/1/edit
  def edit
  end

  # POST /assistances
  # POST /assistances.json
  def create
    @par = assistance_params
    @par[:state] = ""
    @assistance = Assistance.new(@par)

    respond_to do |format|
      if @assistance.save
        format.html { redirect_to @assistance, notice: 'Assistance was successfully created.' }
        format.json { render :show, status: :created, location: @assistance }
      else
        format.html { render :new }
        format.json { render json: @assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assistances/1
  # PATCH/PUT /assistances/1.json
  def update
    session[:return_to] ||= request.referer
    @par = assistance_params
    @par[:state] = ""
    respond_to do |format|
      if @assistance.update(@par)
        format.html { redirect_to session.delete(:return_to), notice: 'Assistance was successfully updated.' }
        format.json { render :show, status: :ok, location: @assistance }
      else
        format.html { render :edit }
        format.json { render json: @assistance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assistances/1
  # DELETE /assistances/1.json
  def destroy
    @assistance.destroy
    respond_to do |format|
      format.html { redirect_to assistances_url, notice: 'Assistance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assistance
      @assistance = Assistance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assistance_params
      params.require(:assistance).permit(:username, :chat, :state)
    end
    
    def assistance_message
        params.require(:assistance).permit(:message)
    end
end

app/helpers/assistances_helper.rb
module AssistancesHelper
end

app/views/assistances/_form.html.erb
<%= form_with(model: assistance, local: true) do |form| %>
  <% if assistance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assistance.errors.count, "error") %> prohibited this assistance from being saved:</h2>
      <ul>
      <% assistance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :assistance_username %>
  </div>

  <div class="field">
    <%= form.label :chat %><br>
    <%= form.text_area :chat, id: :assistance_chat, cols: "125", rows: "20" %>
  </div>
    
  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message, id: :assistance_message %>
  </div>
    <!--
  <div class="actions"> 
     <%= form.submit  "Send message" %>
  </div>-->

  <script>
    async function updatechat(url) {
        var req = new XMLHttpRequest();  
        //var domains = (window.location.href+"");
        //var url = domains.substring(0, domains.length - 5)+".json";
        req.open('GET', url, false);   
        req.send(null);
        if(req.status == 200)
        {   var obj = JSON.parse(req.responseText);
            var chat = document.getElementById("assistance_chat");
            chat.value = obj.chat;
            console.log(obj.chat);
        }
    }
    var chat = document.getElementById("assistance_chat");
    chat.scrollTop = chat.scrollHeight;
    var domains = (window.location.href+"");
    document.getElementById("assistance_chat").readOnly = true;
    if(domains.substring(domains.length - 4, domains.length) === "edit")
    {   var url = domains.substring(0, domains.length - 5)+".json";
        window.setInterval(function(){
            updatechat(url);
        }, 5000);
    }

  </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
    </script>
    <script>
        function sendmessage(){
        $.ajax(
                {
                type : "POST",
                url : "https://fcm.googleapis.com/fcm/send",

                    headers :
                {
                    Authorization : "key=AAAAvnb64Sg:APA91bGpOZxILqmYIRSNFbcD-4ezQZeJrvjFydvgTGCblrmOnTCZktdv1fiTE3N9USd2iD7kAtY0NNlmz_6ey2vLHkNyOM4B4Rcrkf1ykNwFBY6CYNnsmRqNh_i0NSULl7c7MT9DyAK-"
                },

                    contentType : 'application/json',
            data : JSON.stringify(
        {
           "to" : "/topics/valenzarepairs",
           "data":
           {
               "action" : "set_message",
               "message" : $("#assistance_message").val(),
               "user" : $("#assistance_username").val()
           }
       }),

       success : function(response)
       {
           console.log(response);
       },
       error : function(xhr, status, error)
       {
           console.log(xhr.error);
       }
    });
        document.getElementById("assistance_chat").value += "\n[Admin]: "+document.getElementById("assistance_message").value;
    };
    </script>
    <button onClick="sendmessage()">Send Message</button>
<% end %>

app/views/assistances/edit.html.erb
<h1>Editing Assistance</h1>

<%= render 'form', assistance: @assistance %>

<%= link_to 'Show', @assistance %> |
<%= link_to 'Back', assistances_path %>

app/views/assistances/index.html.erb
<style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }
        .topnav {
            overflow: hidden;
            background-color: #333;
        }
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        } 

        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }
</style>
<div class="topnav">
        <a href="./">Home</a>
        <a href="users">Users</a>
        <a href="estimates">Estimates</a>
        <a href="devices">Devices</a>
        <a class="active" href="assistances">Assistances</a>
        <a href="repairs">Repairs</a>
</div>
<p id="notice"><%= notice %></p>

<div style="padding-left:16px">

<h1>Assistances</h1>

<table border="1">
  <thead>
    <tr>
      <th>Username</th>
      <th>Chat</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistances.each do |assistance| %>
      <tr>
        <td><%= assistance.username %></td>
        <td><%= assistance.chat %></td>
        <td style="color:red;font: italic bold"><%= assistance.state %></td>
        <!--<td><%= link_to 'Show', assistance %></td>-->
        <td><%= link_to 'Send a Message', edit_assistance_path(assistance) %></td>
        <td><%= link_to 'Destroy', assistance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <script>
            document.getElementById("state_id").value = "OK";
      </script>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Assistance', new_assistance_path %>
</div>

app/views/assistances/new.html.erb
<h1>New Assistance</h1>

<%= render 'form', assistance: @assistance %>

<%= link_to 'Back', assistances_path %>

app/views/assistances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @assistance.username %>
</p>

<p>
  <strong>Chat:</strong>
  <%= @assistance.chat %>
</p>

<p>
  <strong>State:</strong>
  <%= @assistance.state %>
</p>

<%= link_to 'Edit', edit_assistance_path(@assistance) %> |
<%= link_to 'Back', assistances_path %>