config/routes.rb
Rails.application.routes.draw do
  resources :repairs
  resources :provas
  resources :assistances
  get 'home/index'

  root to: "home#index"
  resources :estimates
  resources :devices
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/repair.rb
class Repair < ApplicationRecord
end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs
  # POST /repairs.json
  def create
      @repair = Repair.new(repair_params)
      respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end  
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair }
      else
        format.html { render :edit }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url, notice: 'Repair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:username, :device, :price, :description, :date)
    end
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/views/repairs/_form.html.erb
<%= form_with(model: repair, local: true) do |form| %>
  <% if repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% repair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :repair_username %>
  </div>

  <div class="field">
    <%= form.label :device %>
    <%= form.text_field :device, id: :repair_device %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :repair_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :repair_description %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :repair_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<h1>Editing Repair</h1>

<%= render 'form', repair: @repair %>

<%= link_to 'Show', @repair %> |
<%= link_to 'Back', repairs_path %>

app/views/repairs/index.html.erb
<style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }
        .topnav {
            overflow: hidden;
            background-color: #333;
        }
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        } 

        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }
</style>
<div class="topnav">
        <a href="./">Home</a>
        <a href="users">Users</a>
        <a href="estimates">Estimates</a>
        <a href="devices">Devices</a>
        <a href="assistances">Assistances</a>
        <a class="active" href="repairs">Repairs</a>
</div>
<div style="padding-left:16px">

<p id="notice"><%= notice %></p>

<h1>Repairs</h1>

<table border="1">
  <thead>
    <tr>
      <th>Username</th>
      <th>Device</th>
      <th>Price</th>
      <th>Description</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= repair.username %></td>
        <td><%= repair.device %></td>
        <td><%= repair.price %></td>
        <td><%= repair.description %></td>
        <td><%= repair.date %></td>
        <td><%= link_to 'Show', repair %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair', new_repair_path %>
</div>

app/views/repairs/new.html.erb
<h1>New Repair</h1>

<%= render 'form', repair: @repair %>

<%= link_to 'Back', repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @repair.username %>
</p>

<p>
  <strong>Device:</strong>
  <%= @repair.device %>
</p>

<p>
  <strong>Price:</strong>
  <%= @repair.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repair.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @repair.date %>
</p>

<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>